# Generated by Django 5.2.10 on 2026-01-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('11', 'Tesoro Nacional'), ('13', 'Recursos Específicos')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_fiscal', models.BooleanField(default=True, help_text='Indica si es dinero fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('es_ejecutora', models.BooleanField(default=False, help_text='Solo UU.CC. del Plan Bienal pueden ejecutar gasto')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificadorGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField(choices=[(1, 'Inciso'), (2, 'Partida Principal'), (3, 'Partida Parcial'), (4, 'Partida Subparcial')])),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='core.clasificadorgasto')),
            ],
        ),
        migrations.CreateModel(
            name='EstructuraProgramatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Programa'), (2, 'Subprograma'), (3, 'Proyecto'), (4, 'Obra'), (5, 'Actividad')])),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='core.estructuraprogramatica')),
            ],
        ),
    ]
