# Generated by Django 5.2.10 on 2026-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadcomponente',
            name='sigla',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadcomponente',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
