# Generated by Django 5.2.10 on 2026-01-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unidadcomponente_sigla_alter_unidadcomponente_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej: Insumos de Limpieza, Internet', max_length=200)),
                ('importe_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='IncisoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 2+3, PROM, RYC PAIS', max_length=100)),
                ('respaldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dev_com', models.DecimalField(decimal_places=2, default=0, help_text='Devengado + Compromiso', max_digits=12)),
            ],
        ),
    ]
