# Generated by Django 5.2.10 on 2026-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gastooperativo_incisocontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='incisocontrol',
            name='cuatrigrama',
            field=models.CharField(default='EMAV', help_text='EMAV, BAPI, FAE2, etc.', max_length=10),
        ),
    ]
