# Generated by Django 5.2.10 on 2026-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incisocontrol_cuatrigrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='incisocontrol',
            name='ff',
            field=models.CharField(blank=True, help_text='Fuente de Financiamiento (Ej: 11)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incisocontrol',
            name='programa',
            field=models.CharField(blank=True, help_text='Ej: 01, 16', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incisocontrol',
            name='subprograma',
            field=models.CharField(blank=True, help_text='Ej: 02, 04', max_length=20, null=True),
        ),
    ]
