# Generated by Django 5.2.10 on 2026-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_incisocontrol_ff_incisocontrol_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incisocontrol',
            name='nota',
            field=models.TextField(blank=True, help_text='Observaciones o notas adicionales', null=True),
        ),
    ]
