# Generated by Django 5.2.10 on 2026-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incisocontrol_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='incisocontrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última modificación'),
        ),
    ]
