# Generated by Django 5.2.10 on 2026-01-26 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_incisocontrol_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInciso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('inciso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.incisocontrol')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
