# Generated by Django 5.2.10 on 2026-01-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historialinciso'),
    ]

    operations = [
        migrations.AddField(
            model_name='incisocontrol',
            name='codigo_unidad',
            field=models.CharField(blank=True, help_text='Ej: 111, 234', max_length=20, null=True),
        ),
    ]
