# Generated by Django 5.2.10 on 2026-01-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clasificadorgasto')),
                ('unidad_autorizada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_recibidos', to='core.unidadcomponente')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_autorizados', to='core.unidadcomponente')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anio', models.IntegerField(help_text='Año fiscal')),
                ('trimestre', models.IntegerField(choices=[(1, '1° Trimestre'), (2, '2° Trimestre'), (3, '3° Trimestre'), (4, '4° Trimestre')])),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CADUCADO', 'Caducado'), ('DEVENGADO', 'Devengado')], default='VIGENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fuentefinanciamiento')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.estructuraprogramatica')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trimestre', models.IntegerField(choices=[(1, '1° Trimestre'), (2, '2° Trimestre'), (3, '3° Trimestre'), (4, '4° Trimestre')])),
                ('clasificador_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clasificadorgasto')),
                ('uucc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.unidadcomponente')),
                ('credito_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='finance.credito')),
            ],
            options={
                'verbose_name': 'Distribución de Crédito',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
        migrations.CreateModel(
            name='ModificacionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPENSACION', 'Compensación Interna'), ('REDISTRIBUCION', 'Redistribución'), ('ENTRE_PROGRAMAS', 'Entre Programas')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_entrada', to='finance.asignacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_salida', to='finance.asignacion')),
            ],
        ),
    ]
