# Generated by Django 5.2.10 on 2026-01-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={},
        ),
        migrations.AddField(
            model_name='asignacion',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para Inciso 4 (Inversión)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_obra', to='core.estructuraprogramatica'),
        ),
    ]
