# Generated by Django 5.2.10 on 2026-01-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_asignacion_options_asignacion_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=255)),
                ('numero_orden', models.CharField(blank=True, max_length=50)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='finance.asignacion')),
            ],
        ),
    ]
