# Generated by Django 5.2.10 on 2026-01-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_compromiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero ingresado (Cuota)', max_digits=12),
        ),
    ]
