# Generated by Django 5.2.10 on 2026-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_credito_monto_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='inciso',
            field=models.CharField(default='', help_text='Inciso', max_length=10),
        ),
        migrations.AddField(
            model_name='credito',
            name='principal',
            field=models.CharField(default='', help_text='Partida Principal', max_length=10),
        ),
    ]
