# Generated by Django 5.2.10 on 2026-01-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_credito_inciso_credito_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='recibido',
            field=models.BooleanField(default=True, help_text='Indica si la cuota ya fue recibida efectivamente'),
        ),
    ]
