# Generated by Django 5.2.10 on 2026-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_credito_recibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='tipo_credito',
            field=models.CharField(choices=[('ASIGNACION', 'Asignación'), ('REFUERZO', 'Refuerzo')], default='ASIGNACION', max_length=20, verbose_name='Tipo de Crédito'),
        ),
    ]
