# Generated by Django 5.2.10 on 2026-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_credito_tipo_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto solicitado por la Unidad/GFH', max_digits=12),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto asignado por GFH', max_digits=12),
        ),
    ]
