# Generated by Django 5.2.10 on 2026-02-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_asignacion_monto_solicitado_alter_asignacion_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='monto_solicitado',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='asignacion_gfh',
            field=models.CharField(blank=True, help_text='Referencia asignada por GFH (Texto/Números)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='solicitud_gfh',
            field=models.CharField(blank=True, help_text='Referencia solicitada por GFH (Texto/Números)', max_length=100, null=True),
        ),
    ]
