# Generated by Django 5.2.10 on 2026-02-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_asignacion_monto_solicitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='objeto',
            field=models.CharField(blank=True, choices=[('2+3', '2+3'), ('PROM', 'PROM'), ('RYC PAIS', 'RYC PAIS'), ('RYC EXTERIOR', 'RYC EXTERIOR'), ('4', '4'), ('GGOO', 'GGOO'), ('SS.BB.', 'SS.BB.'), ('PYV', 'PYV'), ('20', '20'), ('40', '40'), ('50', '50'), ('70', '70'), ('87', '87'), ('90', '90'), ('95', '95'), ('99', '99'), ('Vestuario PACID', 'Vestuario PACID')], help_text='Objeto del Gasto', max_length=50, null=True),
        ),
    ]
