# Generated by Django 5.2.10 on 2026-02-10 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(choices=[('CF', 'Capitán de Fragata'), ('CC', 'Capitán de Corbeta'), ('TN', 'Teniente de Navío'), ('TF', 'Teniente de Fragata'), ('TC', 'Teniente de Corbeta'), ('GU', 'Guardiamarina'), ('SM', 'Suboficial Mayor'), ('SP', 'Suboficial Principal'), ('SI', 'Suboficial Primero'), ('SS', 'Suboficial Segundo'), ('CP', 'Cabo Principal'), ('CI', 'Cabo Primero'), ('CS', 'Cabo Segundo'), ('MR', 'Marinero Primero'), ('M2', 'Marinero Segundo'), ('CV', 'Civil')], max_length=2)),
                ('unidad', models.CharField(default='Escuadrilla Aeronaval', max_length=100)),
                ('rol', models.CharField(choices=[('piloto', 'Piloto'), ('tripulante', 'Tripulante'), ('mecanico', 'Mecánico'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20)),
                ('estado', models.BooleanField(default=True, help_text='Activo / Baja')),
            ],
            options={
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vuelo', 'Ropa de Vuelo'), ('trabajo', 'Ropa de Trabajo')], max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Pantalón de Vuelo, Campera, etc.', max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('talle', models.CharField(max_length=20)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('vida_util_meses', models.PositiveIntegerField(help_text='Vida útil estimada en meses')),
                ('estado', models.CharField(choices=[('deposito', 'En Depósito'), ('asignada', 'Asignada'), ('reparacion', 'En Reparación'), ('fs', 'Fuera de Servicio'), ('baja', 'Baja Definitiva')], default='deposito', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'Alta'), ('asignacion', 'Asignación'), ('devolucion', 'Devolución'), ('reparacion', 'Envío a Reparación'), ('baja', 'Baja'), ('modificacion', 'Modificación de Datos')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(help_text='Usuario que realizó la acción', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='logistica.prenda')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('inicial', 'Dotación Inicial'), ('reemplazo', 'Reemplazo'), ('desgaste', 'Desgaste'), ('campana', 'Campaña'), ('otro', 'Otro')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='logistica.personal')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='logistica.prenda')),
            ],
        ),
    ]
