# Generated by Django 5.2.10 on 2026-02-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('vuelo', 'Ropa de Vuelo'), ('trabajo', 'Ropa de Trabajo')], max_length=20)),
                ('vida_util_sugerida', models.PositiveIntegerField(default=12, help_text='En meses')),
            ],
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=models.CharField(help_text='Ej: Marca, Modelo específico, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='vida_util_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Vida útil estimada en meses', null=True),
        ),
        migrations.CreateModel(
            name='Dotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('piloto', 'Piloto'), ('tripulante', 'Tripulante'), ('mecanico', 'Mecánico'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('renovacion_int', models.PositiveIntegerField(default=12, help_text='Intervalo de renovación en meses')),
                ('tipo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.tipoprenda')),
            ],
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.tipoprenda'),
        ),
    ]
