# Generated by Django 5.2.10 on 2026-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_tipoprenda_remove_prenda_modelo_remove_prenda_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='talle_botas',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talle de Botas'),
        ),
        migrations.AddField(
            model_name='personal',
            name='talle_casco',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talle de Casco'),
        ),
        migrations.AddField(
            model_name='personal',
            name='talle_guantes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talle de Guantes'),
        ),
        migrations.AddField(
            model_name='personal',
            name='talle_overall',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talle de Overall'),
        ),
    ]
